[package]
name = "path-lib"
version = "0.9.20251013"
edition = "2024"

[lib]
name = "aria_path"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
vm-lib = { path = "../../vm-lib" }
opcodes-lib = { path = "../../opcodes-lib" }
