[package]
name = "lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.16.0"
rowan = "0.16.1"
line-index = "0.1.2"
tower-lsp = "0.20.0"
tokio = { version = "1.48.0", features = ["full"] }
parking_lot = "0.12"

[dev-dependencies]
pretty_assertions = "1.4.1"
