permissions:
  contents: write
name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      BIN_TARGETS: "aria"
      DYLIB_CRATES: "aria_file aria_http aria_path aria_platform aria_regex aria_timezone"
      EXTRA_FILES: "CHANGELOG.md"
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ariahomebrewreleaseapp }}
          private-key: ${{ secrets.ariahomebrewreleaseapp }}
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF##refs/tags/}" >> "$GITHUB_ENV"
      - name: Build + package
        shell: bash
        run: ./package.sh
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tgz
            *.tgz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update homebrew tap
        continue-on-error: true
        run: gh workflow run main.yml -f version=${{ env.VERSION }} -R arialang/homebrew-aria
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
