name: SlashFmt

on:
  issue_comment:
    types: [created]

# Needed:
# - issues: write  ‚Üí add üëç reaction
# - contents: write ‚Üí fire repository_dispatch
permissions:
  contents: write
  issues: write
  pull-requests: read

jobs:
  dispatch:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/fmt') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: peter-evans/slash-command-dispatch@v4
        with:
          # Use GITHUB_TOKEN now that it has write perms
          token: ${{ secrets.SLASH_COMMAND_PAT  }}
          reaction-token: ${{ secrets.SLASH_COMMAND_PAT  }}
          commands: fmt
          dispatch-type: repository
          issue-type: pull-request
          repository: ${{ github.repository }}
